### ISSUE TITLE
page isn't redirecting properly

### ISSUE THREAD

**Issue by lordkalki** [coderity/Coderity#22]
page is not opening

url: 127.0.0.1/app/users/install/admin:1

error:
The page isn't redirecting properly

Iceweasel has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

**Comment by MichaelHoughton** [comment]
Hi There

Thanks for posting the issue.

Likely the admin routing isn't turned on.

If you look in:

app/Config/core.php

Do you see something like:

Configure::write('Routing.prefixes', array('admin'));

It should be uncommented.

**Comment by lordkalki** [comment]
ya its work now

you are genious person 
ask a question on quora about Coderity
and now its run succesfully
:+1:

**Comment by MichaelHoughton** [comment]
No worries @lordkalki - happy to help!  Just note, that the plugin version is still largely in development, so if you have any problems, just use the app version which is stable!

**Comment by lordkalki** [comment]
i am using app version right now

**Comment by MichaelHoughton** [comment]
Perfect - enjoy :)

**Comment by lordkalki** [comment]
when i try to upload a pic in page or article
url: http://127.0.0.1/js/kcfinder/browse.php?type=images&CKEditor=PageContent&CKEditorFuncNum=1&langCode=en

Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.
Error 404
127.0.0.1
Apache/2.4.9 (Unix) OpenSSL/1.0.1g PHP/5.5.11 mod_perl/2.0.8-dev Perl/v5.16.3

**Comment by MichaelHoughton** [comment]
You are right - I have made a new ticket for this here:
https://github.com/coderity/app/issues/7

And will get back to you on this - feel free to watch this ticket, and I will update you when I have this fixed.
